### ISSUE TITLE
MightEMacs 9.5.0 Build Issue

### ISSUE THREAD

**Issue by pratikmullick** [italia389/MightEMacs#2]
Hi Rick,

While compiling MightEMacs v9.5.0, the following errors crop in:
```
Building MightEMacs...
cc -std=c99 -funsigned-char -Wall -Wextra -Wsometimes-uninitialized -Wunused -Wno-comment -Wno-missing-field-initializers -Wno-missing-braces -Wno-parentheses -Wno-pointer-sign -Wno-unused-parameter  -O2 -I../include -I/usr/local/include -I/usr/local/include -c -o obj/bind.o ../src/bind.c
cc: error: unrecognized command-line option ‘-Wsometimes-uninitialized’; did you mean ‘-Wmaybe-uninitialized’?
make[1]: *** [Makefile:80: obj/bind.o] Error 1
make: *** [Makefile:56: build] Error 2
```
Details:
OS: Arch Linux Rolling Release

**Comment by italia389** [comment]
To fix this issue, edit linux/Makefile and remove the "-Wsometimes-uninitialized" compiler switch from the CFLAGS parameter, then rebuild MightEMacs.  You may have to remove other warning switches as well that your C compiler complains about.  Most compilers support all the -Wxxx switches in the Makefile, but a few do not, as in this case.  The simple fix is to remove the ones that are not supported.
